entities:
    ticket:
        entity: %diamante.ticket.entity.class%
        processor: Diamante\AutomationBundle\Model\ListedEntity\Processor\TicketProcessor
    comment:
        entity: %diamante.comment.entity.class%
        processor: Diamante\AutomationBundle\Model\ListedEntity\Processor\CommentProcessor
    user:
        entity: %diamante.user.entity.class%
        processor: Diamante\AutomationBundle\Model\ListedEntity\Processor\UserProcessor
