datagrid:
    diamante-branch-grid:
        source:
            type: orm
            query:
                select:
                    - b.id
                    - b.name
                    - b.logo
                from:
                    - { table: %diamante.branch.entity.class%, alias: b }
        properties:
            id: ~
            view_link:
                type:       url
                route:      diamante_branch_view
                params:     [ id ]
            update_link:
                type:       url
                route:      diamante_branch_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      diamante_branch_delete
                params:     [ id ]
        sorters:
            columns:
                name:
                  data_name: b.name
        filters:
            columns:
                name:
                    type: string
                    data_name: b.name
        columns:
            logo:
                label: Logo
                type: twig
                frontend_type: html
                template: DiamanteDeskBundle:Branch:Datagrid/Property/logo.html.twig
            name:
                label: Branch Name
        actions:
            view:
                type:          navigate
                label:         View
                icon:          eye-open
                link:          view_link
                rowAction:     true
                acl_resource:  VIEW;Entity:DiamanteDeskBundle:Branch
            update:
                type:          navigate
                label:         Edit
                icon:          edit
                link:          update_link
                acl_resource:  EDIT;Entity:DiamanteDeskBundle:Branch
            delete:
                type:          delete
                label:         Delete
                icon:          trash
                link:          delete_link
                acl_resource:  DELETE;Entity:DiamanteDeskBundle:Branch
        options:
            entityHint: branches

    diamante-branch-tickets-grid:
        extends: diamante-ticket-grid
        source:
            query:
                where:
                    and:
                        - i.branch = :branch
        filters:
            default:
                status: { value: ['@diamante.ticket.datagrid_status_helper->getOpenStatus'] }

    diamante-ticket-grid:
        source:
            type: orm
            query:
                select:
                    - i.id
                    - i.subject
                    - i.priority
                    - i.status
                    - assignee.id as assigneeId
                    - reporter.id as reporterId
                    - branch.name as branchName
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterFullName
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as assigneeFullName
                    - i.createdAt
                    - i.updatedAt
                from:
                    - { table: DiamanteDeskBundle:Ticket, alias: i }
                join:
                    left:
                        - { join: i.branch, alias: branch }
                        - { join: i.reporter, alias: reporter }
                        - { join: i.assignee, alias: assignee }
        properties:
            id: ~
            view_link:
                type:       url
                route:      diamante_ticket_view
                params:     [ id ]
            update_link:
                type:       url
                route:      diamante_ticket_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      diamante_ticket_delete
                params:     [ id ]
        columns:
            subject:
                label:   Subject
            branchName:
                label:   Branch
            assigneeFullName:
                label:   Assignee
                type:    assignee
            reporterFullName:
                label:   Reporter
            priority:
                label:   Priority
            status:
                label:   Status
            createdAt:
                label:   Created
                frontend_type: datetime
            updatedAt:
                label:   Updated
                frontend_type: datetime
        sorters:
            columns:
                subject:
                  data_name: i.subject
                branchName:
                  data_name: branchName
                assigneeFullName:
                  data_name: assigneeFullName
                reporterFullName:
                  data_name: reporterFullName
                priority:
                  data_name: i.priority
                status:
                  data_name: i.status
                createdAt:
                  data_name: i.createdAt
                updatedAt:
                  data_name: i.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                subject:
                    type:      string
                    data_name: i.subject
                branchName:
                    type:      entity
                    data_name: i.branch
                    options:
                        field_options:
                            class: DiamanteDeskBundle:Branch
                            property: name
                assigneeFullName:
                    type:      string
                    data_name: assignee
                reporterFullName:
                    type:      string
                    data_name: reporter
                priority:
                    type:      string
                    data_name: i.priority
                status:
                    type: choice
                    data_name: i.status
                    options:
                        field_options:
                            multiple: true
                            choices:  @diamante.ticket.datagrid_status_helper->getTicketStatuses
                createdAt:
                    type:      datetime
                    data_name: i.createdAt
                updatedAt:
                    type:      datetime
                    data_name: i.updatedAt
        actions:
            view:
                type:          navigate
                label:         View
                icon:          eye-open
                link:          view_link
                rowAction:     true
                acl_resource:  VIEW;Entity:DiamanteDeskBundle:Ticket
            update:
                type:          navigate
                label:         Update
                icon:          edit
                link:          update_link
                acl_resource:  EDIT;Entity:DiamanteDeskBundle:Ticket
            delete:
                type:          delete
                label:         Delete
                icon:          trash
                link:          delete_link
                acl_resource:  DELETE;Entity:DiamanteDeskBundle:Ticket
        options:
            entityHint: tickets

    diamante-ticket-attachments-grid:
        source:
            type: orm
            query:
                select:
                    - a.id
                    - a.file
                from:
                    - { table: %diamante.attachment.entity.class%, alias: a }
                where:
                    and:
                        - a.ticket = :ticket
        properties:
            id: ~
            view_link:
                type:       url
                route:      diamante_attachment_view
                params:     [ id ]
            delete_link:
                type:       url
                route:      diamante_attachment_delete
                params:     [ id ]
        columns:
            file:
                label: File
        actions:
            view:
                type:          navigate
                label:         View
                icon:          eye-open
                link:          view_link
                rowAction:     true
            delete:
                type:          delete
                label:         Delete
                icon:          trash
                link:          delete_link
