oro_menu_config:
  items:
    customer_management:
      label: 'diamante.user.customer_management'
      route: 'diamante_user_list'
      extras:
        position: 60
  tree:
    application_menu:
      children:
        customer_management: ~


oro_titles:
  diamante_user_create: 'Create user'
  diamante_user_view:   '%%user.fullName%% - DiamanteDesk User'
  diamante_user_update: '%%user.name%% - Update'