oro_menu_config:
    items:
        desk_tab:
            label: 'Desk'
            uri: '#'
            extras:
                position: 100

        diamante_branch_list:
            label: 'Branches'
            route: diamante_branch_list
            extras:
                routes: ['diamante_branch_*']
        diamante_ticket_list:
            label: 'All Tickets'
            route: diamante_ticket_list
            extras:
                routes: ['diamante_ticket_*', 'diamante_comment_*']

        #reports

        diamante_report_list:
            label: 'Reports'
            uri: '#'

        diamante_report_test:
            label: 'Test Report'
            route: diamante_report_view
            routeParameters:
                id: 'test_report'
            extras:
                routes: ['diamante_report_*']

    tree:
        application_menu:
            children:
                desk_tab:
                    children:
                        diamante_branch_list: ~
                        diamante_ticket_list: ~
                        diamante_report_list:
                            children:
                                diamante_report_test: ~

oro_titles:
    diamante_branch_list: ~
    diamante_branch_view: '%%branch.name%%'
    diamante_branch_create: 'Create Branch'
    diamante_branch_update: '%%branch.name%% - Edit'

    diamante_comment_create: 'Add Comment - %%ticket.subject%%'
    diamante_comment_update: 'Edit Comment - %%ticket.subject%%'

    diamante_ticket_list: ~
    diamante_ticket_view: '[%%ticket.key%%] %%ticket.subject%%'
    diamante_ticket_create: 'Create Ticket'
    diamante_ticket_update: '%%ticket.subject%% - Edit'
    diamante_ticket_create_attach: 'Add Attachment'
