placeholders:

    page_title_after:
        items:
            default_branch_notification: ~

items:

    default_branch_notification:
        template: DiamanteDeskBundle::defaultBranchNotification.html.twig
        default_branch: [entity]
