reports:
    tickets_by_priority:
        chart:
            type: bar-chart
            y-axis: value
            x-axis: priority
        source:
            type: dql
            dql: "SELECT t.priority, count(t.priority) as value FROM Diamante\\DeskBundle\\Entity\\Ticket t group by t.priority"

    time_of_response:
        chart:
            type: bar-chart
            y-axis: data_count
            x-axis: data_range
        source:
            type: repository
            repository: "Diamante\\DeskBundle\\Infrastructure\\Persistence\\DoctrineReportRepository::getTimeOfResponseReportData"

    time_of_response_widget:
        chart:
            type: bar-chart
            y-axis: data_count
            x-axis: data_range
        source:
            type: repository
            repository: "Diamante\\DeskBundle\\Infrastructure\\Persistence\\DoctrineReportRepository::getTimeOfResponseReportWidgetData"

    tickets_by_channels:
        chart:
            type: grouped-line-chart
            x-axis: day
            y-axis: data
            group: source
        source:
            type: dql
            dql: "select date(t.createdAt) as day, t.source as source, count(t.source) as data from Diamante\\DeskBundle\\Entity\\Ticket t GROUP BY t.source, day"

    tickets_by_channels_widget:
        chart:
            type: pie-chart
            label: label
            data: data
        source:
            type: dql
            dql: "select t.source as label, count(t.source) as data from  Diamante\\DeskBundle\\Entity\\Ticket t GROUP BY t.source"

    tickets_by_branch:
        chart:
            type: grouped-line-chart
            x-axis: day
            y-axis: data
            group: branch
        source:
            type: dql
            dql: "select date(t.createdAt) as day, b.name as branch, count(t.branch) as data from Diamante\\DeskBundle\\Entity\\Ticket t LEFT JOIN Diamante\\DeskBundle\\Entity\\Branch b WITH b.id = t.branch GROUP BY t.branch, day"

    tickets_by_branch_widget:
        chart:
            type: bar-chart
            y-axis: data
            x-axis: branch
        source:
            type: dql
            dql: "select b.name as branch, count(t.branch) as data from Diamante\\DeskBundle\\Entity\\Ticket t LEFT JOIN Diamante\\DeskBundle\\Entity\\Branch b WITH b.id = t.branch GROUP BY t.branch"

    tickets_timeline:
        chart:
            type: grouped-line-chart
            x-axis: day
            y-axis:
                items:
                    - new
                    - closed
                    - reopen
        source:
            type: dql
            dql: "select date(ttl.date) as day, ttl.new, ttl.closed, ttl.reopen from Diamante\\DeskBundle\\Entity\\TicketTimeline ttl GROUP BY day"
