oro_system_configuration:
    groups:
        diamantedesk_channels_front_group:
            title: 'Web'

    fields:
        diamante_front.registration_required:
            type: choice
            options:
                label: 'Registration Requied'
                choices:
                    - No
                    - Yes

    tree:
        system_configuration:
            platform:
                children:
                    diamantedesk_setup:
                        children:
                            diamantedesk_channels:
                                children:
                                    diamantedesk_channels_front_group:
                                        priority: 160
                                        children:
                                            - diamante_front.registration_required
