placeholders:
    page_title_after:
        items:
            default_branch_notification: ~

items:
    default_branch_notification:
        template: DiamanteDeskBundle::defaultBranchNotification.html.twig
        applicable: @diamante.branch.placeholder->isDefault($entity$)
        data:
          default_branch: [entity]
