diamante_front_bundle:
    resource:     "@DiamanteFrontBundle/Controller/IndexController.php"
    type:         annotation
    prefix:       /diamantefront

diamante_front_confirm:
    path:         /diamantefront/confirm

diamante_front_api_user:
    resource:     "@DiamanteFrontBundle/Controller/UserController.php"
    type:         rest
    prefix:       /diamantefront
