diamante_desk_bundle:
    resource:     "@DiamanteDeskBundle/Controller"
    type:         annotation
    prefix:       /desk

diamante_desk_api_branch:
# @todo alias for service
    resource:     diamante.branch.service
# @todo rename diamante_rest_service
    type:         rest_service
    prefix:       /api/rest/{version}/desk/
    requirements:
        version:  latest|v1
        _format:  xml|json
    defaults:
        version:  latest
        _format:  json
