diamante_front_bundle:
    resource:     "@DiamanteFrontBundle/Controller/IndexController.php"
    type:         annotation
    prefix:       /diamantefront

diamante_front_confirm:
    path:         /diamantefront/confirm

diamante_front_user:
    resource:     "@DiamanteFrontBundle/Controller/UserController.php"
    type:         rest
    prefix:       /diamantefront

diamante_front_api_user:
    resource:     diamante.front.current_user.api.service_diamante
    type:         diamante_rest_service
    prefix:       /api/diamante/rest/{version}/desk/
    requirements:
        version:  latest|v1
        _format:  xml|json
    defaults:
        version:  latest
        _format:  json

diamante_desk_api_reset_password:
    resource:     "@DiamanteFrontBundle/Controller/ResetPasswordController.php"
    type:         rest
    prefix:       /api/diamante_front/rest/{version}/desk/
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
        _format:  json
