diamante_desk_bundle:
    resource:     "@DiamanteFrontBundle/Controller/IndexController.php"
    type:         annotation
    prefix:       /diamantefront

diamante_desk_api_register:
    resource:     "@DiamanteFrontBundle/Controller/RegisterController.php"
    type:         rest
    prefix:       /api/diamante_front/rest/{version}/desk/
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
        _format:  json

diamante_front_api_user:
    resource:     diamante.front.update_user.service
    type:         diamante_rest_service
    prefix:       /api/diamante/rest/{version}/desk/
    requirements:
        version:  latest|v1
        _format:  xml|json
    defaults:
        version:  latest
        _format:  json