oro_menu_config:
    items:
        diamante_branch_list:
            label: 'Branches'
            route: diamante_branch_list
            extras:
                routes: ['diamante_branch_*']
                position: 80
        diamante_ticket_list:
            label: 'All Tickets'
            route: diamante_ticket_list
            extras:
                routes: ['diamante_ticket_*', 'diamante_comment_*']
                position: 90
        dashboard_tab:
            display: false
        oro_calendar_view_default:
            display: false
        activities_tab:
            display: false
        reports_tab:
            display: false
        system_tab:
            display: false
        diamante_config_tab:
          label: 'System'
          uri: '#'
          extras:
              position: 100
    tree:
        application_menu:
            children:
                diamante_branch_list: ~
                diamante_ticket_list: ~
                diamante_config_tab:
                  children:
                    system_configuration: ~
                    users_management:
                      children:
                        user_list: ~
                        user_create: ~
                        user_groups: ~
                        user_roles: ~
                    oro_platform_system_info: ~



oro_titles:
    diamante_branch_list: ~
    diamante_branch_view: '%%branch.name%%'
    diamante_branch_create: 'Create Branch'
    diamante_branch_update: '%%branch.name%% - Edit'

    diamante_comment_create: 'Add Comment - %%ticket.subject%%'
    diamante_comment_update: 'Edit Comment - %%ticket.subject%%'

    diamante_ticket_list: ~
    diamante_ticket_view: '[%%ticket.key%%] %%ticket.subject%%'
    diamante_ticket_create: 'Create Ticket'
    diamante_ticket_update: '%%ticket.subject%% - Edit'
    diamante_ticket_create_attach: 'Add Attachment'
