Diamante\UserBundle\Model\UserDetails:
    accessor_order: alphabetical
    properties:
        type:
          exclude: true
        firstName:
          exclude: true
        lastName:
          exclude: true

    virtual_properties:
        getFullName:
            serialized_name: name
            type: string